### ISSUE TITLE
Deprecate in favor of gulp-handlebars

### ISSUE THREAD

**Issue by lazd** [swelham/gulp-ember-templates#3]
[version 2.2.0 of gulp-handlebars](https://github.com/lazd/gulp-handlebars/releases/tag/v2.2.0) supports using Ember's Handlebars compiler and includes both a [simple example](https://github.com/lazd/gulp-handlebars#compiling-templates-for-use-in-ember-applications) and [complex example](https://github.com/lazd/gulp-handlebars/tree/master/examples/ember) that show how to use it to compile templates for Ember.js.

[`gulp-ember-handlebars` is being deprecated](https://github.com/fuseelements/gulp-ember-handlebars/issues/12#issuecomment-52368159) as a result and it would make sense to do the same here to avoid fragmentation in the community.

@swelham , would you be opposed to [deprecating `gulp-ember-templates`](https://www.npmjs.org/doc/cli/npm-deprecate.html)?

If there is functionality in `gulp-ember-templates` you feel that `gulp-handlebars` does not offer, please file an issue or submit a PR, but be mindful of the [gulp plugin guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) as `gulp-ember-templates` does not adhere to them in its current form. @phated

**Comment by boxinator** [comment]
+1 to @MethodGrab comment. Ive been using gulp-ember-templates cause its the only plugin that actually builds hbs properly for ember.

**Comment by searls** [comment]
I think this issue should be closed as confusing to readers. `gulp-handlebars` requires `ember-handlebars` for compilation, and that module is way, way out of date. Reading the `gulp-handlebars` README from the perspective of an ember user is disingenuous because the version of handlebars being compiled to can't be specified in the same way.

**Comment by lazd** [comment]
@searls, please elaborate on how we can either change the README or the plugin itself to work better with Ember. I'm all ears, and of course, PRs welcome! Note that `gulp-handlebars` does not explicitly rely on `ember-handlebars` -- that seemed to be the best way to get it done when the examples were written. If there's a better way now, let's do it.

I've reached out to @ebryn and the Ember team to have them take a look at `gulp-handlebars` to make sure it'll work nicely with Ember and be ready for HTMLBars.

I think everyone can agree fragmentation in the community doesn't help anyone, and I'd rather have `gulp-handlebars` working great with Ember than have 3 or 4 gulp plugins in various states that compile templates for Ember in a certain way.

Furthermore, this plugin violates the [gulp plugin guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md) by wrapping output for different module types/targets whereas `gulp-handlebars` does not.

Let's unify this! As I'm not an Ember user, help me figure out what's required and I'll do what I can to make it happen.

**Comment by searls** [comment]
@lazd the issue that I had was that there was no apparent way to use `gulp-handlebars` and compile to Handlebars 2.0 or 3.0 because of the dependency on `ember-handlebars`. You might look at just going directly to Handlebars for the Ember case, like someone did in this fork of karma-ember-preprocessor [here](https://github.com/llun/karma-ember-preprocessor/commit/837ecde12681a0736c24af79e6f379f08ba0c5b9)

**Comment by lazd** [comment]
@searls [there is no dependency on `ember-handlebars`](https://github.com/lazd/gulp-handlebars/blob/master/package.json#L6-L21). The [example says you should use it](https://github.com/lazd/gulp-handlebars/tree/master/examples/ember), but clearly that's wrong/out of date.

If it's a matter of using a different compiler, simply pass the handlebars compiler as the [`handlebars` option](https://github.com/lazd/gulp-handlebars#optionshandlebars).

Would that meet Ember's needs? If we're using Handlebars directly, as in `karma-ember-preprocessor`, then `gulp-handlebars` will work with Ember as is, without passing options, using the same `gulp-wrap` options as the existing example. I'm not an Ember user and I honestly don't have the time to fully explore this, so I'd appreciate if someone would give it a try and report back.

**Comment by lazd** [comment]
Has anyone tried passing `ember-template-compiler` as `options.handlebars`? Won't that just work?

```js
var gulp = require('gulp');
var wrap = require('gulp-wrap');
var concat = require('gulp-concat');
var declare = require('gulp-declare');
var handlebars = require('gulp-handlebars');

gulp.task('templates', function() {
  // Load templates from the source/templates/ folder relative to where gulp was executed
  gulp.src('source/templates/**/*.hbs')
    // Compile each Handlebars template source file to a template function using Ember's Handlebars
    .pipe(handlebars({
      handlebars: require('ember-template-compiler')
    }))
    // Wrap each template function in a call to Ember.Handlebars.template
    .pipe(wrap('Ember.Handlebars.template(<%= contents %>)'))
    // Declare template functions with Ember.TEMPLATES according to their path and filename
    .pipe(declare({
      namespace: 'Ember.TEMPLATES',
      noRedeclare: true, // Avoid duplicate declarations
      processName: function(filePath) {
        // Allow nesting based on path using gulp-declare's processNameByPath()
        // You can remove this option completely if you aren't using nested folders
        // Drop the source/templates/ folder from the namespace path by removing it from the filePath
        return declare.processNameByPath(filePath.replace('source/templates/', ''));
      }
    }))
    // Concatenate down to a single file
    .pipe(concat('templates.js'))
    // Write the output into the templates folder
    .pipe(gulp.dest('build/js/'));
});
```

**Comment by lazd** [comment]
`ember-template-compiler` is also horribly out of date, with the latest stable version supporting Handlebars 1.x only. https://github.com/toranb/ember-template-compiler/issues/23

@ebryn, can you weigh in?

**Comment by rwjblue** [comment]
As of Ember 1.10 and above, you must compile templates with the template compiler published with your specific build of Ember. 

See http://emberjs.com/blog/2015/02/05/compiling-templates-in-1-10-0.html for more details.

**Comment by MethodGrab** [comment]
To add to what @rwjblue said; that best way of compiling Ember templates with gulp since 1.10 that I've found is a modified version of [this gist](https://gist.github.com/tomaskikutis/517657c4675ce580b1f7) from the comments on that blog post. It uses **gulp-htmlbars** & the version specific compiler from your bower install of Ember and so far I've not run into any problems with it.

**Comment by lazd** [comment]
@rwjblue, that's super helpful! I'll see if I can make that work.

@MethodGrab, looks like `gulp-htmlbars` is yet-another-plugin that needs to be merged with `gulp-handlebars`. I've filed an issue here https://github.com/mattma/gulp-htmlbars/issues/2
