### ISSUE TITLE
How do you compile components?

### ISSUE THREAD

**Issue by marktheis** [swelham/gulp-ember-templates#7]
Hi.
I can't figure out how to compile components.

I have this in my gulpfile.js:
```
gulp.task('templates', function () {
  gulp.src(src + "templates/**/*.hbs")
    .pipe(emberTemplates({
      compiler: require('./bower_components/ember/ember-template-compiler'),
      isHTMLBars: true
    }))
    .pipe(gulp.dest(src + 'assets/js'));
});
```
I have all my components in templates/components/ but they're compiled as normal templates instead of components.

I'm using the latest version. v0.7.1.

I'm a bit unsure if this plugin does support it, but I believe I saw a recent commit about components.
Anyway, thanks for the plugin.

**Comment by minedev** [comment]
As mentioned in #3 by @MethodGrab you can use [this](https://gist.github.com/tomaskikutis/517657c4675ce580b1f7) task to compile components. Note that it uses **gulp-handlebars** and **gulp-tap** rather than *gulp-ember-templates*, which seems to not support this feature (yet).

**Comment by marktheis** [comment]
Thank you. I completely missed that. I'll use that for now.
