### ISSUE TITLE
Reason for substringing before '/' in transformedName?

### ISSUE THREAD

**Issue by djlimbs** [swelham/gulp-ember-templates#9]
Is there a use case for substringing the '/' in transformedName on line 61 of index.js?

var transformedName = name.split('/').slice(-1)[0].toString();

I've found this line of code breaks the template path to components, making my Ember application break. When I no longer do the .split, my templates compile correctly.

I'd like to submit a pull request but wanted to double check first if there were use cases that needed the transformedName split by '/' and substringed. Please let me know, thanks!

**Comment by swelham** [comment]
This was added by PR #6 to support nested templates.

I guess we could add a check in transformName to see whether or not we are transforming the name for a component, maybe as simple as checking `name.startsWith('component/')`?

Also PR's are always welcome :smiley:

**Comment by djlimbs** [comment]
Excellent suggestion, thanks for the info! PR created
